# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bit-Vector-Named
version:      0.022
version_from: lib/Bit/Vector/Named.pm
installdirs:  site
requires:
    Bit::Vector:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
